// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface PageLayoutHeroV1Block {
  _type: "hero";
  _version: 1;
  _key: string;
  "variant"?: "foto-completa" | "dividido" | "centrado" | null;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "primary_label"?: string | null;
  "primary_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "primary_url"?: string | null;
  "secondary_label"?: string | null;
  "secondary_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "secondary_url"?: string | null;
  "badges"?: string | null;
  "card_title"?: string | null;
  "card_text"?: string | null;
  "shortcuts_title"?: string | null;
  "show_form"?: boolean | null;
}

export type PageLayoutHeroBlock = PageLayoutHeroV1Block;

export interface PageLayoutTrustBarV1Block {
  _type: "trust_bar";
  _version: 1;
  _key: string;
  "items"?: { "icon"?: "corazon" | "escudo" | "reloj" | "luna" | "sol" | "casa" | "hospital" | "calendario" | "usuarios" | "usuario" | "estrella" | "check" | "telefono" | "whatsapp" | "ubicacion" | "cerebro" | "venda" | "manos" | "cama" | "silla-ruedas" | "documento" | "chat" | "sparkles" | "medalla" | "familia" | "cafe" | "pastillas" | "brujula" | null; "text": string }[] | null;
}

export type PageLayoutTrustBarBlock = PageLayoutTrustBarV1Block;

export interface PageLayoutServicesGridV1Block {
  _type: "services_grid";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "mode"?: "todos" | "destacados" | null;
  "limit"?: number | null;
  "style"?: "tarjetas-foto" | "lista-compacta" | null;
}

export type PageLayoutServicesGridBlock = PageLayoutServicesGridV1Block;

export interface PageLayoutCardCarouselV1Block {
  _type: "card_carousel";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "items"?: { "tag"?: string | null; "title": string; "text"?: string | null; "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null; "url"?: string | null; "link_label"?: string | null }[] | null;
}

export type PageLayoutCardCarouselBlock = PageLayoutCardCarouselV1Block;

export interface PageLayoutStepsV1Block {
  _type: "steps";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "items"?: { "icon"?: "corazon" | "escudo" | "reloj" | "luna" | "sol" | "casa" | "hospital" | "calendario" | "usuarios" | "usuario" | "estrella" | "check" | "telefono" | "whatsapp" | "ubicacion" | "cerebro" | "venda" | "manos" | "cama" | "silla-ruedas" | "documento" | "chat" | "sparkles" | "medalla" | "familia" | "cafe" | "pastillas" | "brujula" | null; "title": string; "text"?: string | null }[] | null;
  "cta_label"?: string | null;
  "cta_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "cta_url"?: string | null;
}

export type PageLayoutStepsBlock = PageLayoutStepsV1Block;

export interface PageLayoutFeatureGridV1Block {
  _type: "feature_grid";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "layout"?: "bento" | "cuadricula" | "lista" | null;
  "tone"?: "claro" | "arena" | "bruma" | "oscuro" | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "items"?: { "icon"?: "corazon" | "escudo" | "reloj" | "luna" | "sol" | "casa" | "hospital" | "calendario" | "usuarios" | "usuario" | "estrella" | "check" | "telefono" | "whatsapp" | "ubicacion" | "cerebro" | "venda" | "manos" | "cama" | "silla-ruedas" | "documento" | "chat" | "sparkles" | "medalla" | "familia" | "cafe" | "pastillas" | "brujula" | null; "title": string; "text"?: string | null }[] | null;
}

export type PageLayoutFeatureGridBlock = PageLayoutFeatureGridV1Block;

export interface PageLayoutMediaTextV1Block {
  _type: "media_text";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "body"?: PortableTextBlock[] | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "image_side"?: "derecha" | "izquierda" | null;
  "tone"?: "claro" | "arena" | "bruma" | "oscuro" | null;
  "bullets"?: string | null;
  "cta_label"?: string | null;
  "cta_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "cta_url"?: string | null;
}

export type PageLayoutMediaTextBlock = PageLayoutMediaTextV1Block;

export interface PageLayoutTabsMediaV1Block {
  _type: "tabs_media";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "tabs"?: { "label": string; "title"?: string | null; "body"?: string | null }[] | null;
}

export type PageLayoutTabsMediaBlock = PageLayoutTabsMediaV1Block;

export interface PageLayoutPricingV1Block {
  _type: "pricing";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "note"?: string | null;
  "plans"?: { "name": string; "price"?: number | null; "unit"?: string | null; "description"?: string | null; "features"?: string | null; "cta_label"?: string | null; "highlighted"?: boolean | null }[] | null;
}

export type PageLayoutPricingBlock = PageLayoutPricingV1Block;

export interface PageLayoutZonesGridV1Block {
  _type: "zones_grid";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "note"?: string | null;
}

export type PageLayoutZonesGridBlock = PageLayoutZonesGridV1Block;

export interface PageLayoutComparisonV1Block {
  _type: "comparison";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "col_a"?: string | null;
  "col_b"?: string | null;
  "col_c"?: string | null;
  "rows"?: { "feature": string; "a"?: string | null; "b"?: string | null; "c"?: string | null }[] | null;
}

export type PageLayoutComparisonBlock = PageLayoutComparisonV1Block;

export interface PageLayoutTestimonialsV1Block {
  _type: "testimonials";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "items"?: { "quote": string; "author"?: string | null; "relation"?: string | null; "zone"?: string | null; "rating"?: number | null }[] | null;
}

export type PageLayoutTestimonialsBlock = PageLayoutTestimonialsV1Block;

export interface PageLayoutStatsV1Block {
  _type: "stats";
  _version: 1;
  _key: string;
  "items"?: { "value": string; "label"?: string | null }[] | null;
}

export type PageLayoutStatsBlock = PageLayoutStatsV1Block;

export interface PageLayoutFaqV1Block {
  _type: "faq";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "items"?: { "question": string; "answer": string }[] | null;
}

export type PageLayoutFaqBlock = PageLayoutFaqV1Block;

export interface PageLayoutCtaBandV1Block {
  _type: "cta_band";
  _version: 1;
  _key: string;
  "variant"?: "oscuro" | "claro" | "imagen" | null;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "text"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "primary_label"?: string | null;
  "primary_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "primary_url"?: string | null;
  "secondary_label"?: string | null;
  "secondary_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "secondary_url"?: string | null;
}

export type PageLayoutCtaBandBlock = PageLayoutCtaBandV1Block;

export interface PageLayoutLeadFormV1Block {
  _type: "lead_form";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "text"?: string | null;
  "bullets"?: string | null;
  "service"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
}

export type PageLayoutLeadFormBlock = PageLayoutLeadFormV1Block;

export interface PageLayoutBlogLatestV1Block {
  _type: "blog_latest";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "limit"?: number | null;
  "category"?: string | null;
}

export type PageLayoutBlogLatestBlock = PageLayoutBlogLatestV1Block;

export interface PageLayoutRichTextV1Block {
  _type: "rich_text";
  _version: 1;
  _key: string;
  "body"?: PortableTextBlock[] | null;
  "width"?: "lectura" | "amplio" | null;
}

export type PageLayoutRichTextBlock = PageLayoutRichTextV1Block;

export type PageLayoutBlock = PageLayoutHeroBlock | PageLayoutTrustBarBlock | PageLayoutServicesGridBlock | PageLayoutCardCarouselBlock | PageLayoutStepsBlock | PageLayoutFeatureGridBlock | PageLayoutMediaTextBlock | PageLayoutTabsMediaBlock | PageLayoutPricingBlock | PageLayoutZonesGridBlock | PageLayoutComparisonBlock | PageLayoutTestimonialsBlock | PageLayoutStatsBlock | PageLayoutFaqBlock | PageLayoutCtaBandBlock | PageLayoutLeadFormBlock | PageLayoutBlogLatestBlock | PageLayoutRichTextBlock;

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  layout?: PageLayoutBlock[];
  body?: PortableTextBlock[];
  faqs?: { "question": string; "answer": string }[];
  focus_keyword?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface ServiceLayoutHeroV1Block {
  _type: "hero";
  _version: 1;
  _key: string;
  "variant"?: "foto-completa" | "dividido" | "centrado" | null;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "primary_label"?: string | null;
  "primary_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "primary_url"?: string | null;
  "secondary_label"?: string | null;
  "secondary_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "secondary_url"?: string | null;
  "badges"?: string | null;
  "card_title"?: string | null;
  "card_text"?: string | null;
  "shortcuts_title"?: string | null;
  "show_form"?: boolean | null;
}

export type ServiceLayoutHeroBlock = ServiceLayoutHeroV1Block;

export interface ServiceLayoutTrustBarV1Block {
  _type: "trust_bar";
  _version: 1;
  _key: string;
  "items"?: { "icon"?: "corazon" | "escudo" | "reloj" | "luna" | "sol" | "casa" | "hospital" | "calendario" | "usuarios" | "usuario" | "estrella" | "check" | "telefono" | "whatsapp" | "ubicacion" | "cerebro" | "venda" | "manos" | "cama" | "silla-ruedas" | "documento" | "chat" | "sparkles" | "medalla" | "familia" | "cafe" | "pastillas" | "brujula" | null; "text": string }[] | null;
}

export type ServiceLayoutTrustBarBlock = ServiceLayoutTrustBarV1Block;

export interface ServiceLayoutServicesGridV1Block {
  _type: "services_grid";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "mode"?: "todos" | "destacados" | null;
  "limit"?: number | null;
  "style"?: "tarjetas-foto" | "lista-compacta" | null;
}

export type ServiceLayoutServicesGridBlock = ServiceLayoutServicesGridV1Block;

export interface ServiceLayoutCardCarouselV1Block {
  _type: "card_carousel";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "items"?: { "tag"?: string | null; "title": string; "text"?: string | null; "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null; "url"?: string | null; "link_label"?: string | null }[] | null;
}

export type ServiceLayoutCardCarouselBlock = ServiceLayoutCardCarouselV1Block;

export interface ServiceLayoutStepsV1Block {
  _type: "steps";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "items"?: { "icon"?: "corazon" | "escudo" | "reloj" | "luna" | "sol" | "casa" | "hospital" | "calendario" | "usuarios" | "usuario" | "estrella" | "check" | "telefono" | "whatsapp" | "ubicacion" | "cerebro" | "venda" | "manos" | "cama" | "silla-ruedas" | "documento" | "chat" | "sparkles" | "medalla" | "familia" | "cafe" | "pastillas" | "brujula" | null; "title": string; "text"?: string | null }[] | null;
  "cta_label"?: string | null;
  "cta_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "cta_url"?: string | null;
}

export type ServiceLayoutStepsBlock = ServiceLayoutStepsV1Block;

export interface ServiceLayoutFeatureGridV1Block {
  _type: "feature_grid";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "layout"?: "bento" | "cuadricula" | "lista" | null;
  "tone"?: "claro" | "arena" | "bruma" | "oscuro" | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "items"?: { "icon"?: "corazon" | "escudo" | "reloj" | "luna" | "sol" | "casa" | "hospital" | "calendario" | "usuarios" | "usuario" | "estrella" | "check" | "telefono" | "whatsapp" | "ubicacion" | "cerebro" | "venda" | "manos" | "cama" | "silla-ruedas" | "documento" | "chat" | "sparkles" | "medalla" | "familia" | "cafe" | "pastillas" | "brujula" | null; "title": string; "text"?: string | null }[] | null;
}

export type ServiceLayoutFeatureGridBlock = ServiceLayoutFeatureGridV1Block;

export interface ServiceLayoutMediaTextV1Block {
  _type: "media_text";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "body"?: PortableTextBlock[] | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "image_side"?: "derecha" | "izquierda" | null;
  "tone"?: "claro" | "arena" | "bruma" | "oscuro" | null;
  "bullets"?: string | null;
  "cta_label"?: string | null;
  "cta_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "cta_url"?: string | null;
}

export type ServiceLayoutMediaTextBlock = ServiceLayoutMediaTextV1Block;

export interface ServiceLayoutTabsMediaV1Block {
  _type: "tabs_media";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "tabs"?: { "label": string; "title"?: string | null; "body"?: string | null }[] | null;
}

export type ServiceLayoutTabsMediaBlock = ServiceLayoutTabsMediaV1Block;

export interface ServiceLayoutPricingV1Block {
  _type: "pricing";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "note"?: string | null;
  "plans"?: { "name": string; "price"?: number | null; "unit"?: string | null; "description"?: string | null; "features"?: string | null; "cta_label"?: string | null; "highlighted"?: boolean | null }[] | null;
}

export type ServiceLayoutPricingBlock = ServiceLayoutPricingV1Block;

export interface ServiceLayoutZonesGridV1Block {
  _type: "zones_grid";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "note"?: string | null;
}

export type ServiceLayoutZonesGridBlock = ServiceLayoutZonesGridV1Block;

export interface ServiceLayoutComparisonV1Block {
  _type: "comparison";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "col_a"?: string | null;
  "col_b"?: string | null;
  "col_c"?: string | null;
  "rows"?: { "feature": string; "a"?: string | null; "b"?: string | null; "c"?: string | null }[] | null;
}

export type ServiceLayoutComparisonBlock = ServiceLayoutComparisonV1Block;

export interface ServiceLayoutTestimonialsV1Block {
  _type: "testimonials";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "items"?: { "quote": string; "author"?: string | null; "relation"?: string | null; "zone"?: string | null; "rating"?: number | null }[] | null;
}

export type ServiceLayoutTestimonialsBlock = ServiceLayoutTestimonialsV1Block;

export interface ServiceLayoutStatsV1Block {
  _type: "stats";
  _version: 1;
  _key: string;
  "items"?: { "value": string; "label"?: string | null }[] | null;
}

export type ServiceLayoutStatsBlock = ServiceLayoutStatsV1Block;

export interface ServiceLayoutFaqV1Block {
  _type: "faq";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "items"?: { "question": string; "answer": string }[] | null;
}

export type ServiceLayoutFaqBlock = ServiceLayoutFaqV1Block;

export interface ServiceLayoutCtaBandV1Block {
  _type: "cta_band";
  _version: 1;
  _key: string;
  "variant"?: "oscuro" | "claro" | "imagen" | null;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "text"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "primary_label"?: string | null;
  "primary_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "primary_url"?: string | null;
  "secondary_label"?: string | null;
  "secondary_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "secondary_url"?: string | null;
}

export type ServiceLayoutCtaBandBlock = ServiceLayoutCtaBandV1Block;

export interface ServiceLayoutLeadFormV1Block {
  _type: "lead_form";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "text"?: string | null;
  "bullets"?: string | null;
  "service"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
}

export type ServiceLayoutLeadFormBlock = ServiceLayoutLeadFormV1Block;

export interface ServiceLayoutBlogLatestV1Block {
  _type: "blog_latest";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "limit"?: number | null;
  "category"?: string | null;
}

export type ServiceLayoutBlogLatestBlock = ServiceLayoutBlogLatestV1Block;

export interface ServiceLayoutRichTextV1Block {
  _type: "rich_text";
  _version: 1;
  _key: string;
  "body"?: PortableTextBlock[] | null;
  "width"?: "lectura" | "amplio" | null;
}

export type ServiceLayoutRichTextBlock = ServiceLayoutRichTextV1Block;

export type ServiceLayoutBlock = ServiceLayoutHeroBlock | ServiceLayoutTrustBarBlock | ServiceLayoutServicesGridBlock | ServiceLayoutCardCarouselBlock | ServiceLayoutStepsBlock | ServiceLayoutFeatureGridBlock | ServiceLayoutMediaTextBlock | ServiceLayoutTabsMediaBlock | ServiceLayoutPricingBlock | ServiceLayoutZonesGridBlock | ServiceLayoutComparisonBlock | ServiceLayoutTestimonialsBlock | ServiceLayoutStatsBlock | ServiceLayoutFaqBlock | ServiceLayoutCtaBandBlock | ServiceLayoutLeadFormBlock | ServiceLayoutBlogLatestBlock | ServiceLayoutRichTextBlock;

export interface Service {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  short_title?: string;
  menu_group?: "turno" | "necesidad";
  icon?: "corazon" | "escudo" | "reloj" | "luna" | "sol" | "casa" | "hospital" | "calendario" | "usuarios" | "usuario" | "estrella" | "check" | "telefono" | "whatsapp" | "ubicacion" | "cerebro" | "venda" | "manos" | "cama" | "silla-ruedas" | "documento" | "chat" | "sparkles" | "medalla" | "familia" | "cafe" | "pastillas" | "brujula";
  excerpt?: string;
  price_from?: number;
  price_unit?: string;
  hero_eyebrow?: string;
  hero_subtitle?: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  highlights?: string;
  layout?: ServiceLayoutBlock[];
  body?: PortableTextBlock[];
  faqs?: { "question": string; "answer": string }[];
  service_type?: string;
  order?: number;
  featured?: boolean;
  focus_keyword?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface ZoneLayoutHeroV1Block {
  _type: "hero";
  _version: 1;
  _key: string;
  "variant"?: "foto-completa" | "dividido" | "centrado" | null;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "primary_label"?: string | null;
  "primary_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "primary_url"?: string | null;
  "secondary_label"?: string | null;
  "secondary_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "secondary_url"?: string | null;
  "badges"?: string | null;
  "card_title"?: string | null;
  "card_text"?: string | null;
  "shortcuts_title"?: string | null;
  "show_form"?: boolean | null;
}

export type ZoneLayoutHeroBlock = ZoneLayoutHeroV1Block;

export interface ZoneLayoutTrustBarV1Block {
  _type: "trust_bar";
  _version: 1;
  _key: string;
  "items"?: { "icon"?: "corazon" | "escudo" | "reloj" | "luna" | "sol" | "casa" | "hospital" | "calendario" | "usuarios" | "usuario" | "estrella" | "check" | "telefono" | "whatsapp" | "ubicacion" | "cerebro" | "venda" | "manos" | "cama" | "silla-ruedas" | "documento" | "chat" | "sparkles" | "medalla" | "familia" | "cafe" | "pastillas" | "brujula" | null; "text": string }[] | null;
}

export type ZoneLayoutTrustBarBlock = ZoneLayoutTrustBarV1Block;

export interface ZoneLayoutServicesGridV1Block {
  _type: "services_grid";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "mode"?: "todos" | "destacados" | null;
  "limit"?: number | null;
  "style"?: "tarjetas-foto" | "lista-compacta" | null;
}

export type ZoneLayoutServicesGridBlock = ZoneLayoutServicesGridV1Block;

export interface ZoneLayoutCardCarouselV1Block {
  _type: "card_carousel";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "items"?: { "tag"?: string | null; "title": string; "text"?: string | null; "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null; "url"?: string | null; "link_label"?: string | null }[] | null;
}

export type ZoneLayoutCardCarouselBlock = ZoneLayoutCardCarouselV1Block;

export interface ZoneLayoutStepsV1Block {
  _type: "steps";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "items"?: { "icon"?: "corazon" | "escudo" | "reloj" | "luna" | "sol" | "casa" | "hospital" | "calendario" | "usuarios" | "usuario" | "estrella" | "check" | "telefono" | "whatsapp" | "ubicacion" | "cerebro" | "venda" | "manos" | "cama" | "silla-ruedas" | "documento" | "chat" | "sparkles" | "medalla" | "familia" | "cafe" | "pastillas" | "brujula" | null; "title": string; "text"?: string | null }[] | null;
  "cta_label"?: string | null;
  "cta_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "cta_url"?: string | null;
}

export type ZoneLayoutStepsBlock = ZoneLayoutStepsV1Block;

export interface ZoneLayoutFeatureGridV1Block {
  _type: "feature_grid";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "layout"?: "bento" | "cuadricula" | "lista" | null;
  "tone"?: "claro" | "arena" | "bruma" | "oscuro" | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "items"?: { "icon"?: "corazon" | "escudo" | "reloj" | "luna" | "sol" | "casa" | "hospital" | "calendario" | "usuarios" | "usuario" | "estrella" | "check" | "telefono" | "whatsapp" | "ubicacion" | "cerebro" | "venda" | "manos" | "cama" | "silla-ruedas" | "documento" | "chat" | "sparkles" | "medalla" | "familia" | "cafe" | "pastillas" | "brujula" | null; "title": string; "text"?: string | null }[] | null;
}

export type ZoneLayoutFeatureGridBlock = ZoneLayoutFeatureGridV1Block;

export interface ZoneLayoutMediaTextV1Block {
  _type: "media_text";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "body"?: PortableTextBlock[] | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "image_side"?: "derecha" | "izquierda" | null;
  "tone"?: "claro" | "arena" | "bruma" | "oscuro" | null;
  "bullets"?: string | null;
  "cta_label"?: string | null;
  "cta_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "cta_url"?: string | null;
}

export type ZoneLayoutMediaTextBlock = ZoneLayoutMediaTextV1Block;

export interface ZoneLayoutTabsMediaV1Block {
  _type: "tabs_media";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "tabs"?: { "label": string; "title"?: string | null; "body"?: string | null }[] | null;
}

export type ZoneLayoutTabsMediaBlock = ZoneLayoutTabsMediaV1Block;

export interface ZoneLayoutPricingV1Block {
  _type: "pricing";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "note"?: string | null;
  "plans"?: { "name": string; "price"?: number | null; "unit"?: string | null; "description"?: string | null; "features"?: string | null; "cta_label"?: string | null; "highlighted"?: boolean | null }[] | null;
}

export type ZoneLayoutPricingBlock = ZoneLayoutPricingV1Block;

export interface ZoneLayoutZonesGridV1Block {
  _type: "zones_grid";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "note"?: string | null;
}

export type ZoneLayoutZonesGridBlock = ZoneLayoutZonesGridV1Block;

export interface ZoneLayoutComparisonV1Block {
  _type: "comparison";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "col_a"?: string | null;
  "col_b"?: string | null;
  "col_c"?: string | null;
  "rows"?: { "feature": string; "a"?: string | null; "b"?: string | null; "c"?: string | null }[] | null;
}

export type ZoneLayoutComparisonBlock = ZoneLayoutComparisonV1Block;

export interface ZoneLayoutTestimonialsV1Block {
  _type: "testimonials";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "items"?: { "quote": string; "author"?: string | null; "relation"?: string | null; "zone"?: string | null; "rating"?: number | null }[] | null;
}

export type ZoneLayoutTestimonialsBlock = ZoneLayoutTestimonialsV1Block;

export interface ZoneLayoutStatsV1Block {
  _type: "stats";
  _version: 1;
  _key: string;
  "items"?: { "value": string; "label"?: string | null }[] | null;
}

export type ZoneLayoutStatsBlock = ZoneLayoutStatsV1Block;

export interface ZoneLayoutFaqV1Block {
  _type: "faq";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "subtitle"?: string | null;
  "items"?: { "question": string; "answer": string }[] | null;
}

export type ZoneLayoutFaqBlock = ZoneLayoutFaqV1Block;

export interface ZoneLayoutCtaBandV1Block {
  _type: "cta_band";
  _version: 1;
  _key: string;
  "variant"?: "oscuro" | "claro" | "imagen" | null;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "text"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "primary_label"?: string | null;
  "primary_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "primary_url"?: string | null;
  "secondary_label"?: string | null;
  "secondary_action"?: "cotizar" | "whatsapp" | "enlace" | "llamar" | null;
  "secondary_url"?: string | null;
}

export type ZoneLayoutCtaBandBlock = ZoneLayoutCtaBandV1Block;

export interface ZoneLayoutLeadFormV1Block {
  _type: "lead_form";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "text"?: string | null;
  "bullets"?: string | null;
  "service"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
}

export type ZoneLayoutLeadFormBlock = ZoneLayoutLeadFormV1Block;

export interface ZoneLayoutBlogLatestV1Block {
  _type: "blog_latest";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "title": string;
  "highlight"?: string | null;
  "limit"?: number | null;
  "category"?: string | null;
}

export type ZoneLayoutBlogLatestBlock = ZoneLayoutBlogLatestV1Block;

export interface ZoneLayoutRichTextV1Block {
  _type: "rich_text";
  _version: 1;
  _key: string;
  "body"?: PortableTextBlock[] | null;
  "width"?: "lectura" | "amplio" | null;
}

export type ZoneLayoutRichTextBlock = ZoneLayoutRichTextV1Block;

export type ZoneLayoutBlock = ZoneLayoutHeroBlock | ZoneLayoutTrustBarBlock | ZoneLayoutServicesGridBlock | ZoneLayoutCardCarouselBlock | ZoneLayoutStepsBlock | ZoneLayoutFeatureGridBlock | ZoneLayoutMediaTextBlock | ZoneLayoutTabsMediaBlock | ZoneLayoutPricingBlock | ZoneLayoutZonesGridBlock | ZoneLayoutComparisonBlock | ZoneLayoutTestimonialsBlock | ZoneLayoutStatsBlock | ZoneLayoutFaqBlock | ZoneLayoutCtaBandBlock | ZoneLayoutLeadFormBlock | ZoneLayoutBlogLatestBlock | ZoneLayoutRichTextBlock;

export interface Zone {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  short_title?: string;
  kind?: "localidad" | "barrio" | "sector" | "municipio";
  parent?: string;
  locality?: string;
  neighborhoods?: string;
  excerpt?: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  intro?: PortableTextBlock[];
  landmarks?: { "name": string; "kind"?: "clinica" | "hospital" | "parque" | "centro-comercial" | "otro" | null; "note"?: string | null }[];
  layout?: ZoneLayoutBlock[];
  faqs?: { "question": string; "answer": string }[];
  lat?: number;
  lng?: number;
  order?: number;
  focus_keyword?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  excerpt?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  key_takeaways?: string;
  content?: PortableTextBlock[];
  faqs?: { "question": string; "answer": string }[];
  cta_service?: string;
  reading_minutes?: number;
  focus_keyword?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Site {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  legal_name?: string;
  nit?: string;
  phone_display?: string;
  phone_e164?: string;
  whatsapp_display?: string;
  email?: string;
  address?: string;
  city?: string;
  hours?: string;
  coverage?: string;
  announcement?: string;
  announcement_url?: string;
  header_cta?: string;
  sticky_title?: string;
  sticky_text?: string;
  footer_about?: string;
  footer_legal?: string;
  lead_title?: string;
  lead_eyebrow?: string;
  lead_text?: string;
  lead_schedules?: string;
  lead_relations?: string;
  social?: { "name": string; "url": string }[];
  trust?: { "icon"?: "corazon" | "escudo" | "reloj" | "luna" | "sol" | "casa" | "hospital" | "calendario" | "usuarios" | "usuario" | "estrella" | "check" | "telefono" | "whatsapp" | "ubicacion" | "cerebro" | "venda" | "manos" | "cama" | "silla-ruedas" | "documento" | "chat" | "sparkles" | "medalla" | "familia" | "cafe" | "pastillas" | "brujula" | null; "text": string }[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    services: Service;
    zones: Zone;
    posts: Post;
    site: Site;
  }
}